### ISSUE TITLE
Possible excessive use of lower()

### ISSUE THREAD

**Issue by TomHotston** [MonteClements97/Guess_The_Word#1]
In play file superfluous comprehension lowering case, could use .lower() on whole string.

**Comment by lucyhancock3533** [comment]
If a string was passed into function as opposed to list could drop in replacement line:
`word_list = list(the_word.lower())`
Then using word_list as opposed to the_word. Would require slight changes to main py file.

**Comment by MonteClements97** [comment]
Thank you James, this has been implemented.
